name: Your Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx
        pip install -r requirements.txt  # 或者你的依賴安裝命令

    - name: Run your application
      run: |
        python ./page/8_辨識🛸_yoloV8辨識_🐱.py
