name: Your Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx virtualgl libgl1-nvidia-glx
          pip install -r requirements.txt
          pip install tensorflow streamlit-drawable-canvas numpy==1.23.5 pandas==1.5.3 scikit-learn==1.2.2 tensorflow-cpu scikit-image joblib yfinance catboost ultralytics

      - name: Run your application
        run: python ./pages/8_辨識🛸_yoloV8辨識_🐱.py
