---
name: main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: >
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx
          sudo apt-get install -y virtualgl
          pip install -r requirements.txt
          pip install tensorflow streamlit-drawable-canvas numpy==1.23.5 pandas==1.5.3 scikit-learn==1.2.2 tensorflow-cpu scikit-image joblib yfinance catboost ultralytics
      - name: Create symbolic link for libGL.so.1
        run: |
          sudo ln -s /usr/lib/x86_64-linux-gnu/libGL.so.1 /usr/lib/libGL.so.1

        
